Lesson1
satou-001133/java_training pull request #3
Opened 2024-03-20 04:36 UTC by satou-001133

【概要】
2章実力確認問題のコーディングが完了しました。

【内容】
①Hello World!を表示。
②入力した2つの文字列を結合しHello World!を表示。
③int型の変数X,Yに数値を入れ、入れ替えて表示。
④int型の変数Xに7を代入し3倍の値及び半分の値を表示。

【テスト】
[テスト仕様書]
(https://1drv.ms/x/s!AquYgn3-RTPTdz3WNPt4UCgqPKw)

2024-03-20 11:52 UTC, yu-it-engineer requested changes
コメントしました！
コードが問題の仕様を満たしていないところが多かったためテスト仕様書はまだ確認していません。
まずはコメントの修正をお願いします！

2024-03-20 11:52 UTC, yu-it-engineer commented on HelloWorld/src/Lesson1/Lesson2.java
> +class Lesson2{
packageとclassの間には改行を入れてください！

2024-03-20 11:52 UTC, yu-it-engineer commented on HelloWorld/src/Lesson1/Lesson2.java
> +	System.out.println(hello + "," + world);}
インデントを整えてください！
クラスやメソッドの{}は以下のような形が基本です。

```
public class Sample {
  public void sample() {
    // 処理
  }
}
```

2024-03-20 11:52 UTC, yu-it-engineer commented on HelloWorld/src/Lesson1/Lesson2.java
> +public static void main(String[] args) {
出力される内容は問題で指定されている通りになっていますか？

2024-03-20 11:52 UTC, yu-it-engineer commented on HelloWorld/src/Lesson1/Lesson1.java
> +class Lesson1{
packageとclassの間には改行を入れてください！

2024-03-20 11:52 UTC, yu-it-engineer commented on HelloWorld/src/Lesson1/Lesson1.java
>  		System.out.println("Hello World!");
出力される内容は問題で指定されている通りになっていますか？

2024-03-20 11:52 UTC, yu-it-engineer commented on HelloWorld/src/Lesson1/Lesson3.java
> +class Lesson3
packageとclassの間には改行を入れてください！

2024-03-20 11:52 UTC, yu-it-engineer commented on HelloWorld/src/Lesson1/Lesson3.java
>  		System.out.println("XとYを足すと" + A + "になる");
このコードは正常に動作しますか？
また、問題の意図としては、例えばxに2を代入し、yに3を代入して、xとyの値を入れ替えて出力して欲しいというものです。
そのようなコードになっていますか？

2024-03-20 11:52 UTC, yu-it-engineer commented on HelloWorld/src/Lesson1/Lesson4.java
>  		int X;
以下を修正してください！
・ローカル変数は基本的に小文字で定義してください。
・変数定義時は必ず初期化してください。（意図せず初期化されているか明確に区別するため。）

2024-03-20 11:52 UTC, yu-it-engineer commented on HelloWorld/src/Lesson1/Lesson4.java
>  		Y = (X*3)/2;
演算子の横には半角スペースを入れてください！（見栄え上送するのが通例）
(x * 3) / 2;

2024-03-20 11:52 UTC, yu-it-engineer commented on HelloWorld/src/Lesson1/Lesson4.java
>  		System.out.println("変数Xの3倍をさらに1/2にすると、" + Y);
問題に記載のある表示が不足していませんか？

2024-03-24 07:56 UTC, satou-001133 commented on HelloWorld/src/Lesson1/Lesson2.java
> +class Lesson2{
https://github.com/satou-001133/java_training/blob/java-2-skill-check/HelloWorld/src/Lesson1/Lesson1.java

packageとclassの間に改行を入れました！

2024-03-24 07:57 UTC, satou-001133 commented on HelloWorld/src/Lesson1/Lesson2.java
> +	System.out.println(hello + "," + world);}
https://github.com/satou-001133/java_training/blob/java-2-skill-check/HelloWorld/src/Lesson1/Lesson2.java

インデント処理完了です！
ご確認の程よろしくお願いいたします🙇

2024-03-24 07:58 UTC, satou-001133 commented on HelloWorld/src/Lesson1/Lesson2.java
> +public static void main(String[] args) {
https://github.com/satou-001133/java_training/blob/java-2-skill-check/HelloWorld/src/Lesson1/Lesson2.java

問題内容とコードを確認していたところ、『Hello,World』になっていましたが、誤りでした。
『Hello World』こちらに修正いたしました！

2024-03-24 07:59 UTC, satou-001133 commented on HelloWorld/src/Lesson1/Lesson1.java
> +class Lesson1{
https://github.com/satou-001133/java_training/blob/java-2-skill-check/HelloWorld/src/Lesson1/Lesson1.java

packageとclassの間に改行を入れました！

2024-03-24 08:00 UTC, satou-001133 commented on HelloWorld/src/Lesson1/Lesson1.java
>  		System.out.println("Hello World!");
https://github.com/satou-001133/java_training/blob/java-2-skill-check/HelloWorld/src/Lesson1/Lesson1.java

確認しましたが、異なっている箇所がわかりません💦

2024-03-24 08:00 UTC, satou-001133 commented on HelloWorld/src/Lesson1/Lesson3.java
> +class Lesson3
https://github.com/satou-001133/java_training/blob/java-2-skill-check/HelloWorld/src/Lesson1/Lesson3.java

packageとclassの間に改行を入れました！

2024-03-24 08:11 UTC, satou-001133 commented on HelloWorld/src/Lesson1/Lesson3.java
>  		System.out.println("XとYを足すと" + A + "になる");
https://github.com/satou-001133/java_training/pull/3/commits/e6abc10a30c5ca8c55530e386f68ed579e81ddc3#diff-398d3f2d0cab4c25427d759ea7269505d9767ea880e1feadb86b90757721b1c6

確認したところ、xとyの値は入れ替わっていませんでした🙇
こちら修正リンクになります！
ご確認の程よろしくお願いいたします！

2024-03-24 08:13 UTC, satou-001133 commented on HelloWorld/src/Lesson1/Lesson4.java
>  		Y = (X*3)/2;
https://github.com/satou-001133/java_training/blob/java-2-skill-check/HelloWorld/src/Lesson1/Lesson4.java

演算子の横に半角スペースを入れました！
ご確認の方、よろしくお願いいたします🙇

2024-03-24 08:16 UTC, satou-001133 commented on HelloWorld/src/Lesson1/Lesson4.java
>  		System.out.println("変数Xの3倍をさらに1/2にすると、" + Y);
https://github.com/satou-001133/java_training/blob/java-2-skill-check/HelloWorld/src/Lesson1/Lesson4.java

以下要件は満たしているとは思うのですが、やはり足りていませんでしょうか❓

a) int 型の変数 x に数値 7 を代入する。
b) 変数 x の値を 3 倍にする。
c) 変数 x の値を表示する。
d) 変数 x の値を半分(1/2)にする。
e) 変数 x の値を表示する。

2024-03-24 13:00 UTC, yu-it-engineer requested changes
確認しました！
修正をお願いします！

2024-03-24 13:00 UTC, yu-it-engineer commented on HelloWorld/src/Lesson1/Lesson4.java
> +		System.out.println("変数xの値は、" + 7);
7ではなくxを出力するようにした方が良いです！

2024-03-24 21:54 UTC, satou-001133 commented on HelloWorld/src/Lesson1/Lesson1.java
> +class Lesson1{
https://github.com/satou-001133/java_training/blob/dafb090d9e5502b0daa7bc73bd28879a9e37f11e/HelloWorld/src/Lesson1/Lesson1.java

Java Dcc挿入完了しました！

2024-03-24 21:54 UTC, satou-001133 commented on HelloWorld/src/Lesson1/Lesson1.java
>  	public static void main(String[] args) {
https://github.com/satou-001133/java_training/blob/dafb090d9e5502b0daa7bc73bd28879a9e37f11e/HelloWorld/src/Lesson1/Lesson1.java

こちらもJava Dcc挿入完了しました！

2024-03-24 22:10 UTC, satou-001133 commented on HelloWorld/src/Lesson1/Lesson2.java
> +  }
https://github.com/satou-001133/java_training/blob/java-2-skill-check/HelloWorld/src/Lesson1/Lesson2.java

インデント整えました！

2024-03-24 22:11 UTC, satou-001133 commented on HelloWorld/src/Lesson1/Lesson3.java
> +        System.out.println("xとyを足すと" + a + "になります。");
https://github.com/satou-001133/java_training/blob/java-2-skill-check/HelloWorld/src/Lesson1/Lesson3.java

最後のコードは加算の必要ありませんでした🙇
削除し修正いたしました！

2024-03-24 22:13 UTC, satou-001133 commented on HelloWorld/src/Lesson1/Lesson4.java
> +		int y = (x * 3)/2;
https://github.com/satou-001133/java_training/blob/java-2-skill-check/HelloWorld/src/Lesson1/Lesson4.java

空欄をなくしました！
より見やすいように今後は気をつけます！

2024-03-24 22:13 UTC, satou-001133 commented on HelloWorld/src/Lesson1/Lesson4.java
> +		int y = (x * 3)/2;
インデント修正していなかったため、ただいま修正します🙇

2024-03-24 22:23 UTC, satou-001133 commented on HelloWorld/src/Lesson1/Lesson4.java
> +		System.out.println("変数xの値は、" + 7);
https://github.com/satou-001133/java_training/blob/java-2-skill-check/HelloWorld/src/Lesson1/Lesson4.java

("変数xの値は、" + x);
こちら修正いたしました！
ご確認の程、よろしくお願いいたいします🙇

2024-03-24 22:26 UTC, satou-001133 commented on HelloWorld/src/Lesson1/Lesson4.java
> +		}
https://github.com/satou-001133/java_training/blob/java-2-skill-check/HelloWorld/src/Lesson1/Lesson3.java

ご指摘いただきました、インデントの修正をしました！

2024-03-24 22:27 UTC, satou-001133 commented on HelloWorld/src/Lesson1/Lesson4.java
> +		int y = (x * 3)/2;
https://github.com/satou-001133/java_training/blob/java-2-skill-check/HelloWorld/src/Lesson1/Lesson4.java

こちらもインデント修正しました！

2024-03-25 22:59 UTC, yu-it-engineer requested changes
レビューしました！
ご確認をお願いします！

2024-03-25 22:59 UTC, yu-it-engineer commented on HelloWorld/src/Lesson1/Lesson1.java
> +class Lesson1{
OKです！

2024-03-25 22:59 UTC, yu-it-engineer commented on HelloWorld/src/Lesson1/Lesson1.java
>  	public static void main(String[] args) {
Java Doc追加されていないです！

2024-03-25 22:59 UTC, yu-it-engineer commented on HelloWorld/src/Lesson1/Lesson4.java
> +		}
インデントがおかしいままです！

2024-03-26 11:39 UTC, satou-001133 commented on HelloWorld/src/Lesson1/Lesson4.java
> +		}
https://github.com/satou-001133/java_training/blob/java-2-skill-check/HelloWorld/src/Lesson1/Lesson4.java

何度も申し訳ございません🙇
インデント再調整しました！
ご確認の方、よろしくお願いいたします🙇

2024-03-31 00:01 UTC, yu-it-engineer approved these changes
LGTM！

2024-03-31 00:01 UTC, yu-it-engineer commented on HelloWorld/src/Lesson1/Lesson1.java
>  	public static void main(String[] args) {
OKです！

2024-04-16 05:31 UTC, closed without merging