Java 3 skill check
satou-001133/java_training pull request #4
Opened 2024-04-01 03:03 UTC by satou-001133

【概要】
3章実力確認問題のコーディングが完了しました。

【内容】
⚫︎整数値x・yに任意の数値（点数）を入力し、成績を表示するプログラムを作成。
①ケース1）
　・60点以上：「合格」を表示
　・「60点以上：「不合格」を表示。
②ケース2）
　・80点以上：「たいへんよくできました。」表示。
　・60点以上 80点未満：「よくできました。」を表示。
　・60点未満：「ざんねんでした。」を表示・
③ケース3）
　・80点以上：「優」を表示。
　・70点以上、80点未満：「良」を表示。
　・60点以上、70点以上：「可」を表示。
　・60点未満：「「不可」を表示。

⚫︎整数値x、yに任意の数値（点数）を入力し、下記条件を表示するプログラムを作成。
①xはyより小さく、かつxとyは共に偶数である。
②xとyは等しく、かつ、負の数である。
③xとyより小さい、または、xは偶数である。

【テスト】
[テスト仕様書]
(https://1drv.ms/x/s!AquYgn3-RTPTebPp7YqCVX9kWpg)

2024-04-01 04:58 UTC, yu-it-engineer reviewed
レビューしました。
確認をお願いします。
また、テストケースは最低以下のケースの考慮が必要です。

・閾値チェック
60条件の分岐点の場合
59、60、61
・マトリクス
条件となる項目を掛け合わせた数のケースが必要です。
48ケース = 
xが正か負か(2ケース) × yが正か負か(2ケース) × xが偶数か奇数か(2ケース) × yが偶数か奇数か(2ケース) × xよりyが大きいか等しいか(3ケース)
![Uploading image.png…]()

2024-04-01 04:58 UTC, yu-it-engineer commented on HelloWorld/src/Lesson2/Lesson2_1.java
> +/**
importの下には改行をお願いします！

2024-04-01 04:58 UTC, yu-it-engineer commented on HelloWorld/src/Lesson2/Lesson2_1.java
> + */
JavaDocを2つつけてはいけません！

2024-04-01 04:58 UTC, yu-it-engineer commented on HelloWorld/src/Lesson2/Lesson2_1.java
> +	public static void main(String[] args)throws IOException{
メソッドにもJavaDocが必要です！
同じ指摘はなくしていきましょう！

2024-04-01 04:58 UTC, yu-it-engineer commented on HelloWorld/src/Lesson2/Lesson2_1.java
> +		if (res >= 60) {
if-elseは以下のように半角スペースを入れてください。

```
if () {
} else if () {
} else {
}
```

2024-04-01 04:58 UTC, yu-it-engineer commented on HelloWorld/src/Lesson2/Lesson2_1.java
> +		if (res >= 60) {
101や0を入力した場合どうなりますか？

2024-04-01 04:58 UTC, yu-it-engineer commented on HelloWorld/src/Lesson2/Lesson2_2.java
> +		if(x < y && x % 2 ==0 && y % 2  == 0) {
演算子の横に半角スペースがありません。
同じ指摘は減らしていきましょう。

2024-04-01 04:58 UTC, yu-it-engineer commented on HelloWorld/src/Lesson2/Lesson2_2.java
> +		}
インデントは統一しましょう。
if-elseの{}の中のコードの最終行の下は改行を入れますか？入れませんか？

2024-04-01 04:58 UTC, yu-it-engineer commented on HelloWorld/src/Lesson2/Lesson2_2.java
> +		}else if(x < y && x % 2 == 0) {
条件が間違っていませんか？
動作確認はしましたか？

2024-04-04 01:56 UTC, satou-001133 commented on HelloWorld/src/Lesson2/Lesson2_1.java
> +/**
遅くなりました🙇
imaportの下に改行入れました！
ご確認の程、よろしくお願いいたします🙇

https://github.com/satou-001133/java_training/blob/java-3-skill-check/HelloWorld/src/Lesson2/Lesson2_1.java

2024-04-04 01:56 UTC, satou-001133 commented on HelloWorld/src/Lesson2/Lesson2_1.java
> + */
こちらもとの【ケース1〜3】を一つにまとめ、簡潔にしましたが認識あっていますでしょうか？
ご確認の程よろしくお願いいたします🙇

https://github.com/satou-001133/java_training/blob/java-3-skill-check/HelloWorld/src/Lesson2/Lesson2_1.java

2024-04-04 01:56 UTC, satou-001133 commented on HelloWorld/src/Lesson2/Lesson2_1.java
> +	public static void main(String[] args)throws IOException{
メソッドに
@param args　コマンドの引数　出力される文字列、数値を指定
のJava Dccを挿入しました。
承知しました！
何度も同じご指摘をいただき、ありがとうございます🙇
以後気をつけます！
こちらもご確認の方よろしくお願いいたします！

https://github.com/satou-001133/java_training/blob/java-3-skill-check/HelloWorld/src/Lesson2/Lesson2_1.java

2024-04-04 01:56 UTC, satou-001133 commented on HelloWorld/src/Lesson2/Lesson2_1.java
> +		if (res >= 60) {
こちら半角スペース挿入しました！
よろしくお願いいたします！

https://github.com/satou-001133/java_training/blob/java-3-skill-check/HelloWorld/src/Lesson2/Lesson2_1.java

2024-04-04 01:56 UTC, satou-001133 commented on HelloWorld/src/Lesson2/Lesson2_1.java
> +		if (res >= 60) {
ご確認いただいたコードで「0」「101」を実行させたところ、不要な結果まで表示されていました。
こちら修正し、「0」や「101」などの範囲外の数値を入力すると、再入力するようプログラムし直しました。
if文の後にreturn;を追加しました！
ご確認の程、よろしくお願いいたします！

https://github.com/satou-001133/java_training/blob/java-3-skill-check/HelloWorld/src/Lesson2/Lesson2_1.java

2024-04-04 01:56 UTC, satou-001133 commented on HelloWorld/src/Lesson2/Lesson2_2.java
> +		if(x < y && x % 2 ==0 && y % 2  == 0) {
演算子の横に半角スペースを挿入しました🙇
ご確認の程よろしくお願いいたします！

https://github.com/satou-001133/java_training/blob/java-3-skill-check/HelloWorld/src/Lesson2/Lesson2_2.java

2024-04-04 01:56 UTC, satou-001133 commented on HelloWorld/src/Lesson2/Lesson2_2.java
> +		}
こちら全てに改行を入れておりましたが、
改行をなくし、統一させました！
ご確認の程よろしくお願いいたします🙇

https://github.com/satou-001133/java_training/blob/java-3-skill-check/HelloWorld/src/Lesson2/Lesson2_2.java

2024-04-04 01:57 UTC, satou-001133 commented on HelloWorld/src/Lesson2/Lesson2_2.java
> +		}else if(x < y && x % 2 == 0) {
条件が誤っておりました。
「負の整数」と記載していたところ、「負の数」で修正いたしました。
動作については、x・y両方に-3を代入したところ無事に出力されます。
ご確認の程よろしくお願いいたします🙇

https://github.com/satou-001133/java_training/blob/java-3-skill-check/HelloWorld/src/Lesson2/Lesson2_2.java

2024-04-07 02:05 UTC, yu-it-engineer requested changes
レビューしました！
テスト仕様書はファイルを直接アップロードいただけると助かります！

2024-04-07 02:12 UTC, satou-001133 commented
ご確認いただき、ありがとうございます！
仕様書のアップロードの件、承知しました🙇
次回からそのようにさせていただきます🙇
いつも細かく確認していただき、ありがとうございます！

2024年4月7日(日) 11:05 yu-it-engineer ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> レビューしました！
> テスト仕様書はファイルを直接アップロードいただけると助かります！
> ------------------------------
>
> In HelloWorld/src/Lesson2/Lesson2_1.java
> <https://github.com/satou-001133/java_training/pull/4#discussion_r1554450014>
> :
>
> > @@ -0,0 +1,59 @@
> +package Lesson2;
> +
> +import java.io.BufferedReader;
> +import java.io.IOException;
> +import java.io.InputStreamReader;
> +/**
>
> OKです！
> ------------------------------
>
> In HelloWorld/src/Lesson2/Lesson2_1.java
> <https://github.com/satou-001133/java_training/pull/4#discussion_r1554450543>
> :
>
> > +/**
> + * 【ケース 1】
> + * 60 点以上：「合格」
> + * * 60 点未満：「不合格」
> + *
> + * 【ケース 2】
> + * 80 点以上：「たいへんよくできました。」
> + * 60 点以上、80 点未満：「よくできました。」
> + * 60 点未満：「ざんねんでした。」
> + *
> + * 【ケース 3】
> + * 80 点以上：「優」
> + * 70 点以上、80 点未満：「良」
> + * 60 点以上、70 点未満：「可」
> + * 60 点未満：「不可」
> + */
>
> OKです！
> ------------------------------
>
> In HelloWorld/src/Lesson2/Lesson2_1.java
> <https://github.com/satou-001133/java_training/pull/4#discussion_r1554450913>
> :
>
> > + * 60 点以上：「合格」
> + * * 60 点未満：「不合格」
> + *
> + * 【ケース 2】
> + * 80 点以上：「たいへんよくできました。」
> + * 60 点以上、80 点未満：「よくできました。」
> + * 60 点未満：「ざんねんでした。」
> + *
> + * 【ケース 3】
> + * 80 点以上：「優」
> + * 70 点以上、80 点未満：「良」
> + * 60 点以上、70 点未満：「可」
> + * 60 点未満：「不可」
> + */
> +class Lesson2_1{
> +	public static void main(String[] args)throws IOException{
>
> 以下の書き方としましょう！
>
> /**
>  * メソッドの説明
>  * @param 変数名 変数の説明
>  * @return 返却値の説明
>  */
>
> ------------------------------
>
> In HelloWorld/src/Lesson2/Lesson2_1.java
> <https://github.com/satou-001133/java_training/pull/4#discussion_r1554451051>
> :
>
> > + * 80 点以上：「優」
> + * 70 点以上、80 点未満：「良」
> + * 60 点以上、70 点未満：「可」
> + * 60 点未満：「不可」
> + */
> +class Lesson2_1{
> +	public static void main(String[] args)throws IOException{
> +		System.out.println("試験の点数を入力してください。");
> +		
> +		BufferedReader br =
> +				new BufferedReader(new InputStreamReader(System.in));
> +		
> +		String str = br.readLine();
> +		int res = Integer.parseInt(str);
> +
> +		if (res >= 60) {
>
> OKです！
> ------------------------------
>
> In HelloWorld/src/Lesson2/Lesson2_1.java
> <https://github.com/satou-001133/java_training/pull/4#discussion_r1554451125>
> :
>
> > + * 80 点以上：「優」
> + * 70 点以上、80 点未満：「良」
> + * 60 点以上、70 点未満：「可」
> + * 60 点未満：「不可」
> + */
> +class Lesson2_1{
> +	public static void main(String[] args)throws IOException{
> +		System.out.println("試験の点数を入力してください。");
> +		
> +		BufferedReader br =
> +				new BufferedReader(new InputStreamReader(System.in));
> +		
> +		String str = br.readLine();
> +		int res = Integer.parseInt(str);
> +
> +		if (res >= 60) {
>
> OKです！
> ------------------------------
>
> In HelloWorld/src/Lesson2/Lesson2_2.java
> <https://github.com/satou-001133/java_training/pull/4#discussion_r1554451238>
> :
>
> > +		System.out.println("yの値を入力してください。");
> +		String str2  = br.readLine();
> +		int y = Integer.parseInt(str2);
> +		
> +		if(x < y && x % 2 ==0 && y % 2  == 0) {
> +			System.out.println(x + "は" + y + "より小さく、かつ、" + x + "と" + y + "は共に偶数である。");
> +			
> +		}else if(x == y && x < 0) {
> +			System.out.println(x + "と" + y + "は等しく、かつ、負の整数である。");
> +			
> +		}else if(x < y && x % 2 == 0) {
> +			System.out.println(x + "は" + y + "より小さい。または" + x + "は偶数である。");
> +			
> +		}else {
> +			System.out.println("もう一度入力してください。");
> +		}
>
> OKです！
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/satou-001133/java_training/pull/4#pullrequestreview-1984391878>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BG4I25KOBCAIFCK3C7CPCP3Y4CSWVAVCNFSM6AAAAABFQ6YVUGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSOBUGM4TCOBXHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-04-09 04:16 UTC, satou-001133 commented on HelloWorld/src/Lesson2/Lesson2_1.java
> +	public static void main(String[] args)throws IOException{
お疲れ様です！
メソッドの書き方を修正いたしました。
ご確認の程、よろしくお願いいたいます🙇

https://github.com/satou-001133/java_training/blob/java-3-skill-check/HelloWorld/src/Lesson2/Lesson2_1.java

2024-04-16 05:30 UTC, closed without merging