第4章 実力問題（for文）
satou-001133/java_training pull request #5
Opened 2024-04-12 09:25 UTC by satou-001133

【概要】
第4章実力確認問題のコーディングが完了しました。

【内容】
《問題1》
・保険契約者の情報を出力し、出力の最後に遅延利息が発生している人数を出力する。
    保険契約者一覧はString配列に格納
 
 【保険契約者一覧】
| 契約者名 | 保険料 | 遅延利息金 |
| ---- | ---- | ---- |
| 中村 | 5000 | 2000 |
| 田島 | 3000 |  |
| 小澤 | 4500 |  |
| 大西 | 6000 | 3500 |

《問題2》
・商品/単価/支払金額を3回入力し、支払金額の不足有無を出力。
    最後に不足の合計を出力。
    入力値はString配列に格納し、数値の計算はStringから変換を実施。

【テスト】
[テスト仕様書]
[4章_テスト仕様書 (4月12日).xlsx](https://github.com/satou-001133/java_training/files/14956764/4._.4.12.xlsx)

2024-04-12 09:27 UTC, satou-001133 commented
第4章 実力問題 完了いたしました。
ご確認の程、よろしくお願いいたします🙇

https://github.com/satou-001133/java_training/blob/java-4-skill-check/HelloWorld/src/Lesson3/Lesson3_1.java

2024-04-12 09:29 UTC, satou-001133 commented
こちらもご確認をお願いいたします🙇

【4_2】
https://github.com/satou-001133/java_training/blob/java-4-skill-check/HelloWorld/src/Lesson3/Lesson3_2.java

2024-04-12 17:37 UTC, yu-it-engineer requested changes
全体的に問題の条件を満たしていない点が見られます。
現場でも仕様通りに作ることが求められるので今一度しっかりと問題文を確認してください。

2024-04-12 17:37 UTC, yu-it-engineer commented on HelloWorld/src/Lesson3/Lesson3_1.java
> +		System.out.println("【保険契約者一覧】");
String配列を使用してください！

2024-04-12 17:37 UTC, yu-it-engineer commented on HelloWorld/src/Lesson3/Lesson3_2.java
> +		System.out.println("商品を入力してください。");
for文の中はインデントをつけてください！

2024-04-12 17:37 UTC, yu-it-engineer commented on HelloWorld/src/Lesson3/Lesson3_2.java
> +		int shortage = y - x; //支払金額不足額を算出
※入力値はString配列に格納すること。
これが満たされていません！

2024-04-13 23:43 UTC, satou-001133 commented on HelloWorld/src/Lesson3/Lesson3_1.java
> +		System.out.println("【保険契約者一覧】");
問題を再度見直し、全体的に修正させていただきました🙇
String配列についてのページを読んでいなかったため、読んだのちに修正いたしました！
ご確認の程、よろしくお願いいたします！

https://github.com/satou-001133/java_training/blob/java-4-skill-check/HelloWorld/src/Lesson3/Lesson3_1.java

2024-04-13 23:44 UTC, satou-001133 commented on HelloWorld/src/Lesson3/Lesson3_2.java
> +		System.out.println("商品を入力してください。");
こちらインデントを見直しました🙇
ご確認の程、よろしくお願いいたします！

https://github.com/satou-001133/java_training/blob/java-4-skill-check/HelloWorld/src/Lesson3/Lesson3_2.java

2024-04-13 23:51 UTC, satou-001133 commented on HelloWorld/src/Lesson3/Lesson3_2.java
> +		System.out.println("商品を入力してください。");
{

↑こちらの位置が不適切であったため、再度調整しました。
ご確認の程、よろしくお願いいたします！

https://github.com/satou-001133/java_training/blob/java-4-skill-check/HelloWorld/src/Lesson3/Lesson3_2.java

2024-04-13 23:52 UTC, satou-001133 commented on HelloWorld/src/Lesson3/Lesson3_2.java
> +		int shortage = y - x; //支払金額不足額を算出
こちらもString配列に格納し、再度条件を確認しました。

ご確認の程、よろしくお願いいたします🙇

https://github.com/satou-001133/java_training/blob/java-4-skill-check/HelloWorld/src/Lesson3/Lesson3_2.java

2024-04-16 05:30 UTC, closed without merging